#!/usr/bin/env bash

bspc config top_padding $PANEL_HEIGHT
bspc config window_gap      15

# border Colors
bspc config normal_border_color   \#110000
bspc config focused_border_color  \#00BFFF
bspc config active_border_color   \#110000
bspc config presel_feedback_color \#000BFF

# Add desktops to monitors
bspc monitor LVDS --reset-desktops 1 2 3 4 5 6 7 8 9 10

# Focus 
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   true
bspc config pointer_follows_monitor true

bspc config split_ratio             0.52
bspc config border_width            2
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single monocle          true

# Panels and notifications
polybar LVDS &
/usr/lib/notify-osd/notify-osd &
battmon --interval 5 --delta 3 --low 10 --critical 3 --dark &

# Rules
bspc rule -a qutebrowser desktop='^2'
bspc rule -a transmission-gtk state=floating
bspc rule -a Transmission-gtk state=floating
bspc rule -a nm-connection-editor state=floating center=true
bspc rule -a Nm-connection-editor state=floating center=true
bspc rule -a VirtualBox Manager state=floating center=true
bspc rule -a VirtualBox Manager state=floating center=true


# Scratchpads
bspc rule -a '*:_scratch' state=floating center=true
bspc rule -a '*:_htop' state=floating center=true

# reload tree so bspwm can be reloaded
if [ -e "$BSPWM_STATE" ] ; then
	bspc wm -l "$BSPWM_STATE"
	rm "$BSPWM_STATE"
fi

