# This is an example (nonsense) configuration file for udiskie.

program_options:
  tray: auto
  # flat or nested
  menu: nested
  automount: false
  notify: true
  file_manager: "kitty -e yazi"
  terminal: "kitty"
  password_prompt:
    [
      "zenity",
      "--entry",
      "--hide-text",
      "--text",
      "Enter Password for {device_presentation}:",
    ]

#device_config:
#  device_file: /dev/dm-5 # [filter]
#  ignore: false # [action] never ignore this device
#  id_uuid: 9d53-13ba # [filter] match by device UUID
#  options: [noexec, nodev] # [action] mount options can be given as list
#  automount: false # [action] do not automount this device
#  id_type: vfat # [filter] match file system type
#  ignore: true # [action] ignore all FAT devices

#  - id_type: ntfs # [filter] (optional)
#    skip: true
#  - ignore: True # never mount/unmount or even show this in the GUI
#    automount: False # show but do not automount this device
#    options: [] # additional options to be passed when mounting

#notifications:
# Customize which notifications are shown for how long. Possible
# values are:
#  positive number         timeout in seconds
#  false                   disable
#  -1                      use the libnotify default timeout

#  timeout: 1.5 # set the default for all notifications

# Specify only if you want to overwrite the default:
#  device_mounted: 5 # mount notification
#  device_unmounted: false # unmount notification
#  device_added: false # device has appeared
#  device_removed: false # device has disappeared
#  device_unlocked: -1 # encrypted device was unlocked
#  device_locked: -1 # encrypted device was locked
#  job_failed: -1 # mount/unlock/.. has failed

quickmenu_actions: [mount, unmount, unlock, terminal, detach, delete]
# List of actions to be shown in the quickmenu or the special value 'all'.
# The quickmenu is shown on left-click if using flat menu type.

notification_actions:
  # Define which actions should be shown on notifications. Note that there
  # are currently only a limited set of actions available for each
  # notification. Events that are not explicitly specified show the default
  # set of actions. Specify an empty list if you don't want to see any
  # notification for the specified event:

  device_mounted: [browse]
  device_added: [mount]

icon_names:
  media: [drive-removable-media, media-optical]
  browse: [document-open, folder-open]
  terminal: [terminal, kitty, xfce-terminal]
  mount: [udiskie-mount]
  unmount: [udiskie-unmount]
  unlock: [udiskie-unlock]
  lock: [udiskie-lock]
  eject: [udiskie-eject, media-eject]
  detach: [udiskie-detach]
  delete: [udiskie-eject]
  quit: [application-exit]
