#!/usr/bin/env bash
    _            _       _   _       __ _
#  | |_  ___ _ _| |__ __| |_| |_  _ / _| |___ __ ___ __
#  | ' \/ -_) '_| '_ (_-<  _| | || |  _|  _\ V  V / '  \
#  |_||_\___|_| |_.__/__/\__|_|\_,_|_|  \__|\_/\_/|_|_|_|
#  ========================================= Autostart ===


# import google color schemes
BIN="$HOME/.config/herbstluftwm/bin"
. ${BIN}/gmc

hc() {
    herbstclient "$@"
}

hc emit_hook reload


twmnd &

#battmon --interval 5 --delta 3 --low 10 --critical 3 --dark &

# remove all existing keybindings
hc keyunbind --all

####################################################################### keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-Escape quit
hc keybind $Mod-Escape reload
hc keybind $Mod-Shift-Delete close_and_remove
hc keybind $Mod-Delete close
hc keybind $Mod-Return spawn ${TERMINAL}

######################################################## basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h  focus left
hc keybind $Mod-j  focus down
hc keybind $Mod-k    focus up
hc keybind $Mod-l focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h  shift left
hc keybind $Mod-Shift-j  shift down
hc keybind $Mod-Shift-k    shift up
hc keybind $Mod-Shift-l shift right

####################################################### splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-Control-Left  split   left    0.5
hc keybind $Mod-Control-Down  split   bottom  0.5
hc keybind $Mod-Control-Right split   right   0.5
hc keybind $Mod-Control-Up    split   top     0.5
hc keybind $Mod-Control-h  split   left    0.5
hc keybind $Mod-Control-j  split   bottom  0.5
hc keybind $Mod-Control-k split   right   0.5
hc keybind $Mod-Control-l    split   top     0.5

# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Alt-Left    resize left +$resizestep
hc keybind $Mod-Alt-Down    resize down +$resizestep
hc keybind $Mod-Alt-Up      resize up +$resizestep
hc keybind $Mod-Alt-Right   resize right +$resizestep
hc keybind $Mod-Alt-h    resize left +$resizestep
hc keybind $Mod-Alt-j    resize down +$resizestep
hc keybind $Mod-Alt-k      resize up +$resizestep
hc keybind $Mod-Alt-l   resize right +$resizestep

########################################################
# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-Tab                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button3 zoom
hc mousebind $Mod-Button2 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#00BFFF'
hc set frame_border_normal_color '#000000'
hc set frame_bg_normal_color '#0000FF'
hc set frame_bg_active_color '#0000ff'
hc set frame_border_width 2
hc set always_show_frame 0
hc set frame_bg_transparent 100
#hc set frame_active_opacity 100
#hc set frame_normal_opacity 100
hc set frame_transparent_width 0
hc set frame_gap 4

hc attr theme.active.color '#0000FF'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 10
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set focus_follows_mouse 0

################ APPS ##############################
hc keybind $Mod+Shift+Return spawn qutebrowser
hc keybind $Mod+space spawn dmenu_extended_run
hc keybind $Mod+Shift+space spawn adams_menu
hc keybind $Mod+b spawn tor-browser-en
hc keybind $Mod+w spawn wing6.1
hc keybind $Mod+q spawn qtcreator
hc keybind $Mod+a spawn atom



################### ScratchPad ##################
hc keybind F1 spawn $BIN/q3terminal.sh

############### Media Keys #########################
hc keybind XF86AudioLowerVolume spawn amixer set Master 2%- && notify-send " Volume Lowered To $(alsavol -d) "
hc keybind XF86AudioRaiseVolume spawn amixer set Master 2%+ && notify-send " Volume Raised By 1 "
hc keybind XF86AudioMute spawn amixer -q set PCM toggle && notify-send " Volume Muted "


# rules
hc unrule -F
hc rule class=qutebrowser tag=2 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on


############################ Read up on #################################################
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
#hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' fullscreen=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off



hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel="$BIN"/panel
#panel="$BIN"/hlwm-dzen2
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done

#"$BIN/"pulsar &



# vim: tw=80
