windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAMgAAAAEgAABj8AAAODAAADIgAAABQAAAY9AAADgQAAAAAAAAAABkAAAAMiAAAA
    FAAABj0AAAOB
  tabs:
  - history:
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'GitHub - fogine/rofi-search: Interactive Google / DuckDuckGo search
        via rofi'
      url: https://github.com/fogine/rofi-search
      zoom: 1.0
    - pinned: false
      title: rofi-search/rofi-search at master · fogine/rofi-search · GitHub
      url: https://github.com/fogine/rofi-search/blob/master/rofi-search
  - history:
    - pinned: false
      title: kill in top at DuckDuckGo
      url: https://duckduckgo.com/?q=kill+in+top&ia=web
    - pinned: false
      title: rofi-blocks at DuckDuckGo
      url: https://duckduckgo.com/?q=rofi-blocks&ia=software
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'GitHub - OmarCastro/rofi-blocks: A Rofi modi that allows controlling
        rofi content throug communication with an external program'
      url: https://github.com/OmarCastro/rofi-blocks
      zoom: 1.0
  - active: true
    history:
    - pinned: false
      title: qutebrowser/qute-pass at master · qutebrowser/qutebrowser · GitHub
      url: https://github.com/qutebrowser/qutebrowser/blob/master/misc/userscripts/qute-pass
    - pinned: false
      title: qutebrowser/misc/userscripts at master · qutebrowser/qutebrowser · GitHub
      url: https://github.com/qutebrowser/qutebrowser/tree/master/misc/userscripts
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 2157
      title: 'GitHub - LaurenceWarne/qute-code-hint: A Qutebrowser user script for
        hinting and copying code'
      url: https://github.com/LaurenceWarne/qute-code-hint
      zoom: 1.0
  - history:
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: qutebrowser execvp not found at DuckDuckGo
      url: https://duckduckgo.com/?q=qutebrowser+execvp+not+found&ia=software
      zoom: 1.0
