windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAPCAAAAFQAAB3oAAAQyAAADxAAAABcAAAd4AAAEMAAAAAAAAAAAB4AAAAPEAAAA
    FwAAB3gAAAQw
  tabs:
  - history:
    - active: true
      last_visited: '2025-03-29T14:46:53'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: dotfiles/qutebrowser/config.py at master · The-Compiler/dotfiles · GitHub
      url: https://github.com/The-Compiler/dotfiles/blob/master/qutebrowser/config.py
      zoom: 1.0
  - active: true
    history:
    - active: true
      last_visited: '2025-03-29T14:46:53'
      pinned: false
      scroll-pos:
        x: 0
        y: 160
      title: how to add themes to qutebrowser - Google Search
      url: https://www.google.com/search?q=how%20to%20add%20themes%20to%20qutebrowser
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-03-29T14:46:52'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'Vim: How do you efficiently search for text? - Super User'
      url: https://superuser.com/questions/345215/vim-how-do-you-efficiently-search-for-text
      zoom: 1.0
