windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAAAAAAEAAABj8AAAODAAAAAgAAABIAAAY9AAADgQAAAAAAAAAABkAAAAACAAAA
    EgAABj0AAAOB
  tabs:
  - history:
    - pinned: false
      title: 11.04 - How can I change brightness through terminal - Ask Ubuntu
      url: https://askubuntu.com/questions/56155/how-can-i-change-brightness-through-terminal
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 952
      title: herbstluftwm panel at DuckDuckGo
      url: https://duckduckgo.com/?q=herbstluftwm+panel&ia=web
      zoom: 1.0
    - pinned: false
      title: howtos [herbstluftwm wiki]
      url: http://wiki.herbstluftwm.org/howtos
  - active: true
    history:
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 823
      title: 'GitHub - rendom/panel: Herbstluftwm panel (Dzen/Lemonbar)'
      url: https://github.com/rendom/panel
      zoom: 1.0
