windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAAAAAAEgAAA78AAAQ3AAAAAQAAABMAAAO+AAAENgAAAAAAAAAAB4AAAAABAAAA
    EwAAA74AAAQ2
  tabs:
  - history:
    - active: true
      last_visited: '2025-05-05T11:21:34'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: using fasd in zsh - Google Search
      url: https://www.google.com/search?q=using%20fasd%20in%20zsh
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-05T11:21:33'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'Excellent vi mode for kitty terminal : r/KittyTerminal'
      url: https://www.reddit.com/r/KittyTerminal/comments/159mekd/excellent_vi_mode_for_kitty_terminal/
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-05T11:21:28'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Analyze disk usage in Linux like a pro with ncdu - oh, ok.
      url: https://ohok.org/analyze-disk-usage-in-linux-like-a-pro-with-ncdu/
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-05T11:21:33'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'How to have seamless copy between the kitty terminal and applications
        in Vim mode : r/KittyTerminal'
      url: https://www.reddit.com/r/KittyTerminal/comments/1hz17sn/how_to_have_seamless_copy_between_the_kitty/
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-05T11:21:33'
      pinned: false
      scroll-pos:
        x: 0
        y: 840
      title: 'How to have seamless copy between the kitty terminal and applications
        in Vim mode : r/KittyTerminal'
      url: https://www.reddit.com/r/KittyTerminal/comments/1hz17sn/how_to_have_seamless_copy_between_the_kitty/
      zoom: 1.0
  - active: true
    history:
    - last_visited: '2025-05-05T12:13:07'
      pinned: false
      title: "mikesmithgh/kitty-scrollback.nvim: \U0001F63D Open your Kitty scrollback
        buffer with Neovim. Ameowzing!"
      url: https://github.com/mikesmithgh/kitty-scrollback.nvim?tab=readme-ov-file
    - active: true
      last_visited: '2025-05-05T12:13:18'
      pinned: false
      scroll-pos:
        x: 0
        y: 4413
      title: "mikesmithgh/kitty-scrollback.nvim: \U0001F63D Open your Kitty scrollback
        buffer with Neovim. Ameowzing!"
      url: https://github.com/mikesmithgh/kitty-scrollback.nvim?tab=readme-ov-file#-installation
      zoom: 1.0
    - last_visited: '2025-05-05T12:13:12'
      pinned: false
      title: "folke/lazy.nvim: \U0001F4A4 A modern plugin manager for Neovim"
      url: https://github.com/folke/lazy.nvim
  - history:
    - active: true
      last_visited: '2025-05-05T11:29:42'
      pinned: false
      scroll-pos:
        x: 0
        y: 1560
      title: 'kutsan/zsh-system-clipboard: System clipboard key bindings for Zsh Line
        Editor with vi mode. It is similar to what `set clipboard=unnamed` does for
        vim.'
      url: https://github.com/kutsan/zsh-system-clipboard
      zoom: 1.0
  - history:
    - last_visited: '2025-05-05T11:21:34'
      pinned: false
      title: 'Vi mode for kitty · kovidgoyal/kitty · Discussion #6485'
      url: https://github.com/kovidgoyal/kitty/discussions/6485
    - active: true
      last_visited: '2025-05-05T11:25:53'
      pinned: false
      scroll-pos:
        x: 0
        y: 5800
      title: "mikesmithgh/kitty-scrollback.nvim: \U0001F63D Open your Kitty scrollback
        buffer with Neovim. Ameowzing!"
      url: https://github.com/mikesmithgh/kitty-scrollback.nvim
      zoom: 1.0
