windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAACAAAAGQAAB30AAAQ1AAAAAwAAABoAAAd8AAAENAAAAAAAAAAAB4AAAAADAAAA
    GgAAB3wAAAQ0
  tabs:
  - history:
    - active: true
      last_visited: '2025-04-13T16:23:55'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Extra keyboard keys - ArchWiki
      url: https://wiki.archlinux.org/title/Extra_keyboard_keys#Non-standard_keyboards
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-13T16:23:55'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Configuring keyboards - LQWiki
      url: https://wiki.linuxquestions.org/wiki/Configuring_keyboards#Enabling_Keyboard_Multimedia_Keys
      zoom: 1.0
  - active: true
    history:
    - last_visited: '2025-04-13T16:23:56'
      pinned: false
      title: prevent picom from making lemobar ttransparent - Google Search
      url: https://www.google.com/search?q=prevent%20picom%20from%20making%20lemobar%20ttransparent
    - active: true
      last_visited: '2025-04-13T16:24:06'
      pinned: false
      scroll-pos:
        x: 0
        y: 240
      title: command to lock from terminal - Google Search
      url: https://www.google.com/search?q=command%20to%20lock%20from%20terminal
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-13T16:23:57'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'eza-community/eza: A modern alternative to ls'
      url: https://github.com/eza-community/eza
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-13T16:23:57'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'mihalea/bitwarden-pyro: Bitwarden python interface built on Rofi, allowing
        for fast selection and insertion of passwords'
      url: https://github.com/mihalea/bitwarden-pyro
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-13T16:23:55'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: ~steef/snixembed - proxy StatusNotifierItems as XEmbedded systemtray-spec
        icons - sourcehut git
      url: https://git.sr.ht/~steef/snixembed
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-13T16:23:56'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: windoiwtype of lemonbar - Google Search
      url: https://www.google.com/search?q=windoiwtype%20of%20lemonbar
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-13T16:23:58'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'domsson/succade: Run, feed and style your Lemonbar with ease'
      url: https://github.com/domsson/succade
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-13T16:23:56'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: what is the wintype of a panel lemonbar - Google Search
      url: https://www.google.com/search?q=what%20is%20the%20wintype%20of%20a%20panel%20lemonbar
      zoom: 1.0
