windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAABAAAAFAAAB34AAAQ2AAAAAgAAABUAAAd9AAAENQAAAAAAAAAAB4AAAAACAAAA
    FQAAB30AAAQ1
  tabs:
  - history:
    - active: true
      last_visited: '2025-04-15T09:01:18'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Dunst - ArchWiki
      url: https://wiki.archlinux.org/title/Dunst
      zoom: 1.0
  - history:
    - last_visited: '2025-04-15T09:41:15'
      pinned: false
      title: pacman -=list orphganed depenencies - Google Search
      url: https://www.google.com/search?q=pacman%20-%3Dlist%20orphganed%20depenencies
    - last_visited: '2025-04-15T09:41:22'
      pinned: false
      title: pacman/Tips and tricks - ArchWiki
      url: https://wiki.archlinux.org/title/Pacman/Tips_and_tricks
    - active: true
      last_visited: '2025-04-15T10:04:42'
      pinned: false
      scroll-pos:
        x: 0
        y: 960
      title: tmux open a terminal in a new window of the same session - Google Search
      url: https://www.google.com/search?q=tmux%20open%20a%20terminal%20in%20a%20new%20window%20of%20the%20same%20session
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-15T10:05:41'
      pinned: false
      scroll-pos:
        x: 0
        y: 1480
      title: using multiple terminal x-windows with one tmux session - Unix & Linux
        Stack Exchange
      url: https://unix.stackexchange.com/questions/282365/using-multiple-terminal-x-windows-with-one-tmux-session
      zoom: 1.0
  - history:
    - last_visited: '2025-04-15T10:05:45'
      pinned: false
      title: A beginner's guide to tmux
      url: https://www.redhat.com/en/blog/introduction-tmux-linux
    - last_visited: '2025-04-15T10:15:23'
      pinned: false
      title: tmux differnce sessions and winbdows - Google Search
      url: https://www.google.com/search?q=tmux%20differnce%20sessions%20and%20winbdows
    - last_visited: '2025-04-15T10:16:09'
      pinned: false
      title: 'Multiple Sessions vs multiple windows on single session : r/tmux'
      url: https://www.reddit.com/r/tmux/comments/pclrty/multiple_sessions_vs_multiple_windows_on_single/
    - last_visited: '2025-04-15T10:18:43'
      pinned: false
      title: open a terminal in same tmux session but a differnt window - Google Search
      url: https://www.google.com/search?q=open%20a%20terminal%20in%20same%20tmux%20session%20but%20a%20differnt%20window
    - last_visited: '2025-04-15T10:19:04'
      pinned: false
      title: shell script - Tmux - Open a new session in another terminal window without
        blocking the calling terminal - Unix & Linux Stack Exchange
      url: https://unix.stackexchange.com/questions/506137/tmux-open-a-new-session-in-another-terminal-window-without-blocking-the-callin
    - last_visited: '2025-04-15T10:21:20'
      pinned: false
      title: bash -n - Google Search
      url: https://www.google.com/search?q=bash%20-n
    - last_visited: '2025-04-15T10:21:35'
      pinned: false
      title: Bash - GNU Project - Free Software Foundation
      url: https://www.gnu.org/software/bash/
    - last_visited: '2025-04-15T10:26:21'
      pinned: false
      title: bash programming $@ - Google Search
      url: https://www.google.com/search?q=bash%20programming%20%20%24%40
    - last_visited: '2025-04-15T10:26:25'
      pinned: false
      title: linux - What does $@ mean in a shell script? - Stack Overflow
      url: https://stackoverflow.com/questions/9994295/what-does-mean-in-a-shell-script
    - last_visited: '2025-04-15T11:06:47'
      pinned: false
      title: copy multplie file in yazi - Google Search
      url: https://www.google.com/search?q=copy%20multplie%20file%20in%20yazi
    - active: true
      last_visited: '2025-04-15T11:06:52'
      pinned: false
      scroll-pos:
        x: 0
        y: 347
      title: Yazi Keyboard Shortcuts Quick Reference - Adamsdesk KB
      url: https://kb.adamsdesk.com/application/yazi-keyboard-shortcuts/
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-15T11:06:42'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: yazi.nvim/README.md at main · mikavilpas/yazi.nvim
      url: https://github.com/mikavilpas/yazi.nvim/blob/main/README.md
      zoom: 1.0
  - history:
    - last_visited: '2025-04-15T10:24:12'
      pinned: false
      title: Bash Scripting Tutorial - Ryans Tutorials
      url: https://ryanstutorials.net/bash-scripting-tutorial/
    - active: true
      last_visited: '2025-04-15T10:24:40'
      pinned: false
      scroll-pos:
        x: 0
        y: 1640
      title: If Statements - Bash Scripting Tutorial
      url: https://ryanstutorials.net/bash-scripting-tutorial/bash-if-statements.php
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-15T10:24:15'
      pinned: false
      scroll-pos:
        x: 0
        y: 1240
      title: Bash Scripting Tutorial – Linux Shell Script and Command Line for Beginners
      url: https://www.freecodecamp.org/news/bash-scripting-tutorial-linux-shell-script-and-command-line-for-beginners/
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-15T11:29:03'
      pinned: false
      scroll-pos:
        x: 0
        y: 1440
      title: plugins/git.yazi at main · yazi-rs/plugins
      url: https://github.com/yazi-rs/plugins/tree/main/git.yazi
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-15T11:29:10'
      pinned: false
      scroll-pos:
        x: 0
        y: 640
      title: plugins/vcs-files.yazi at main · yazi-rs/plugins
      url: https://github.com/yazi-rs/plugins/tree/main/vcs-files.yazi
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-15T11:29:15'
      pinned: false
      scroll-pos:
        x: 0
        y: 200
      title: plugins/piper.yazi at main · yazi-rs/plugins
      url: https://github.com/yazi-rs/plugins/tree/main/piper.yazi
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-15T11:29:20'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: plugins/smart-filter.yazi at main · yazi-rs/plugins
      url: https://github.com/yazi-rs/plugins/tree/main/smart-filter.yazi
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-15T11:29:31'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: plugins/diff.yazi at main · yazi-rs/plugins
      url: https://github.com/yazi-rs/plugins/tree/main/diff.yazi
      zoom: 1.0
  - history:
    - last_visited: '2025-04-15T11:10:53'
      pinned: false
      title: copy paste in yazi - Google Search
      url: https://www.google.com/search?q=copy%20paste%20in%20yazi
    - last_visited: '2025-04-15T11:11:53'
      pinned: false
      title: Yazi Keyboard Shortcuts Quick Reference - Adamsdesk KB
      url: https://kb.adamsdesk.com/application/yazi-keyboard-shortcuts/
    - last_visited: '2025-04-15T11:14:19'
      pinned: false
      title: yazi caopy paste not working - Google Search
      url: https://www.google.com/search?q=yazi%20caopy%20paste%20not%20working
    - last_visited: '2025-04-15T11:15:54'
      pinned: false
      title: '[RFC] Switch to move/copy concept instead of yank/cut/paste · Issue
        #319 · sxyazi/yazi'
      url: https://github.com/sxyazi/yazi/issues/319
    - last_visited: '2025-04-15T11:16:25'
      pinned: false
      title: nnn linux - Google Search
      url: https://www.google.com/search?q=nnn%20linux
    - last_visited: '2025-04-15T11:16:39'
      pinned: false
      title: 'jarun/nnn: n³ The unorthodox terminal file manager'
      url: https://github.com/jarun/nnn
    - last_visited: '2025-04-15T11:17:12'
      pinned: false
      title: copy paste in yazi - Google Search
      url: https://www.google.com/search?q=copy%20paste%20in%20yazi
    - last_visited: '2025-04-15T11:17:52'
      pinned: false
      title: Tips | Yazi
      url: https://yazi-rs.github.io/docs/tips/
    - last_visited: '2025-04-15T11:19:07'
      pinned: false
      title: select multiple files in yazi - Google Search
      url: https://www.google.com/search?q=select%20multiple%20files%20in%20yazi
    - active: true
      last_visited: '2025-04-15T11:22:56'
      pinned: false
      scroll-pos:
        x: 0
        y: 720
      title: 'How are people using their CLI file explorers like yazi with helix to
        any effect? : r/HelixEditor'
      url: https://www.reddit.com/r/HelixEditor/comments/1chvan1/how_are_people_using_their_cli_file_explorers/
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-15T11:23:46'
      pinned: false
      scroll-pos:
        x: 0
        y: 694
      title: 'Allow zellij run CLI command to block until command has completed ·
        Issue #3018 · zellij-org/zellij'
      url: https://github.com/zellij-org/zellij/issues/3018#issuecomment-2086166900
      zoom: 1.0
  - history:
    - last_visited: '2025-04-15T11:38:11'
      pinned: false
      title: yazi coni fig file example - Google Search
      url: https://www.google.com/search?q=yazi%20coni%20fig%20file%20example
    - active: true
      last_visited: '2025-04-15T11:38:18'
      pinned: false
      scroll-pos:
        x: 0
        y: 1000
      title: Configuration | Yazi
      url: https://yazi-rs.github.io/docs/configuration/overview/
      zoom: 1.0
  - active: true
    history:
    - last_visited: '2025-04-15T11:40:04'
      pinned: false
      title: mingo99/yazi.config
      url: https://github.com/mingo99/yazi.config
    - active: true
      last_visited: '2025-04-15T11:40:14'
      pinned: false
      scroll-pos:
        x: 0
        y: 2920
      title: yazi.config/keymap.toml at main · mingo99/yazi.config
      url: https://github.com/mingo99/yazi.config/blob/main/keymap.toml
      zoom: 1.0
