windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAABAAAAFAAAB34AAAQ2AAAAAwAAABYAAAd8AAAENAAAAAAAAAAAB4AAAAADAAAA
    FgAAB3wAAAQ0
  tabs:
  - history:
    - active: true
      last_visited: '2025-04-01T10:45:31'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: (1) New Messages!
      url: https://www.pluralsight.com/resources/blog/cloud/tmux-cheat-sheet
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-01T10:45:32'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: filechoose qutebrowser - Google Search
      url: https://www.google.com/search?q=filechoose%20qutebrowser
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-01T10:45:31'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: NetworkManager - ArchWiki
      url: https://wiki.archlinux.org/title/NetworkManager
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-01T10:45:31'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'systray error: failed to register: The name is not activatable - Google
        Search'
      url: https://www.google.com/search?q=+systray+error%3A+failed+to+register%3A+The+name+is+not+activatable&sca_esv=6cae8d09a1050544&sxsrf=AHTn8zo4lRit6twGQH3oeLdqiOiYkgtyiA%3A1743443089076&ei=kdTqZ-anBKSA5OMP68ScgAs&ved=0ahUKEwimtIrQ77SMAxUkAHkGHWsiB7AQ4dUDCBA&uact=5&oq=+systray+error%3A+failed+to+register%3A+The+name+is+not+activatable&gs_lp=Egxnd3Mtd2l6LXNlcnAiPyBzeXN0cmF5IGVycm9yOiBmYWlsZWQgdG8gcmVnaXN0ZXI6IFRoZSBuYW1lIGlzIG5vdCBhY3RpdmF0YWJsZTIEEAAYHkjfGVCGClibFHABeAGQAQCYAdkBoAHqC6oBBTAuNi4zuAEDyAEA-AEBmAICoALeAcICChAAGLADGNYEGEeYAwCIBgGQBgiSBwUxLjAuMaAHyAY&sclient=gws-wiz-serp
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-01T10:45:31'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'How can I set yazi as default file/folder picker? · sxyazi/yazi · Discussion
        #281'
      url: https://github.com/sxyazi/yazi/discussions/281
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-01T10:45:31'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: xdg-desktop-portal-termfilechooser/contrib/yazi-wrapper.sh at 3ca52f7b0135eed375b05d5fed84d589f0620af5
        · boydaihungst/xdg-desktop-portal-termfilechooser
      url: https://github.com/boydaihungst/xdg-desktop-portal-termfilechooser/blob/3ca52f7b0135eed375b05d5fed84d589f0620af5/contrib/yazi-wrapper.sh
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-01T10:45:32'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: boydaihungst/xdg-desktop-portal-termfilechooser at 3ca52f7b0135eed375b05d5fed84d589f0620af5
      url: https://github.com/boydaihungst/xdg-desktop-portal-termfilechooser/tree/3ca52f7b0135eed375b05d5fed84d589f0620af5
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-01T10:45:32'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'picharly/cyberghostvpn-gui: Cyberghost VPN Linux GUI written in Go.'
      url: https://github.com/picharly/cyberghostvpn-gui
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-01T10:45:32'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'pizzaMan5000/CyberGhostLinuxGUI: Simple java frontend for the Linux
        command-line app for CyberGhost VPN.'
      url: https://github.com/pizzaMan5000/CyberGhostLinuxGUI
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-01T10:45:31'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: exquo
      url: https://github.com/exquo
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-01T10:45:32'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'How can I set yazi as default file/folder picker? · sxyazi/yazi · Discussion
        #281'
      url: https://github.com/sxyazi/yazi/discussions/281
      zoom: 1.0
  - history:
    - last_visited: '2025-04-01T10:45:32'
      pinned: false
      title: adding trayer to barpyrus - Google Search
      url: https://www.google.com/search?q=adding%20trayer%20to%20barpyrus
    - last_visited: '2025-04-01T10:46:06'
      pinned: false
      title: tmux split horizontal - Google Search
      url: https://www.google.com/search?q=tmux%20split%20horizontal
    - last_visited: '2025-04-01T11:54:10'
      pinned: false
      title: gmrun - Google Search
      url: https://www.google.com/search?q=gmrun
    - active: true
      last_visited: '2025-04-01T11:54:19'
      pinned: false
      scroll-pos:
        x: 0
        y: 1520
      title: Gmrun - ArchWiki
      url: https://wiki.archlinux.org/title/Gmrun
      zoom: 1.0
  - active: true
    history:
    - active: true
      last_visited: '2025-04-01T11:54:17'
      pinned: false
      scroll-pos:
        x: 0
        y: 1440
      title: 'wdlkmpx/gmrun: A run utiliy featuring a slim design and bash style auto-completion.'
      url: https://github.com/wdlkmpx/gmrun
      zoom: 1.0
