windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAPAAAAAFAAAB34AAAQ2AAADwQAAABUAAAd9AAAENQAAAAAAAAAAB4AAAAPBAAAA
    FQAAB30AAAQ1
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2025-04-21T16:03:15'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: "\U0001F4F0 What's new? | LazyVim"
      url: http://www.lazyvim.org/news
      zoom: 1.0
