windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAPAAAAAFAAAB34AAAQ2AAADwQAAABUAAAd9AAAENQAAAAAAAAAAB4AAAAPBAAAA
    FQAAB30AAAQ1
  tabs:
  - history:
    - active: true
      last_visited: '2025-04-26T21:45:21'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Bash Scripting Tutorial - Ryans Tutorials
      url: https://ryanstutorials.net/bash-scripting-tutorial/
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-26T21:45:21'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: usinmg yazi as filepicker qutebrowser - Google Search
      url: https://www.google.com/search?q=usinmg%20yazi%20as%20filepicker%20qutebrowser
      zoom: 1.0
  - active: true
    history:
    - active: true
      last_visited: '2025-04-26T21:45:21'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: dots/src/dot_config/qutebrowser/config.py at main · dogeystamp/dots
      url: https://github.com/dogeystamp/dots/blob/main/src/dot_config/qutebrowser/config.py
      zoom: 1.0
