windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAPAAAAAAAAAB38AAAQ3AAADwQAAAAEAAAd+AAAENgAAAAAAAAAAB4AAAAPBAAAA
    AQAAB34AAAQ2
  tabs:
  - history:
    - active: true
      last_visited: '2025-05-12T10:22:41'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: ohmyzsh/plugins at master · ohmyzsh/ohmyzsh
      url: https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-12T10:22:41'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: ohmyzsh/plugins/copybuffer at master · ohmyzsh/ohmyzsh
      url: https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/copybuffer
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-12T10:22:41'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'Bitwarden userscript sudenly quit working · Issue #8198 · qutebrowser/qutebrowser'
      url: https://github.com/qutebrowser/qutebrowser/issues/8198
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-12T10:22:35'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Avalon Williams / qutebrowser-bitwarden-dmenu · GitLab
      url: https://gitlab.com/AGitBoy/qutebrowser-bitwarden-dmenu
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-12T10:22:41'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'mattydebie/bitwarden-rofi: Wrapper for Bitwarden https://github.com/bitwarden/cli
        and Rofi'
      url: https://github.com/mattydebie/bitwarden-rofi
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-12T10:22:41'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: ohmyzsh/plugins/eza at master · ohmyzsh/ohmyzsh
      url: https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/eza
      zoom: 1.0
  - active: true
    history:
    - last_visited: '2025-05-12T10:22:40'
      pinned: false
      title: Hints - kitty
      url: https://sw.kovidgoyal.net/kitty/kittens/hints/
    - last_visited: '2025-05-12T10:35:27'
      pinned: false
      title: xmonad actions navigatioj2d - Google Search
      url: https://www.google.com/search?q=xmonad%20actions%20navigatioj2d
    - active: true
      last_visited: '2025-05-12T10:40:31'
      pinned: false
      scroll-pos:
        x: 0
        y: 896
      title: XMonad.Actions.Navigation2D
      url: https://hackage.haskell.org/package/xmonad-contrib-0.18.1/docs/XMonad-Actions-Navigation2D.html
      zoom: 1.0
    - last_visited: '2025-05-12T10:38:20'
      pinned: false
      title: XMonad Configuration Tutorial | xmonad - the tiling window manager that
        rocks
      url: https://xmonad.org/TUTORIAL.html#customizing-xmonad
