windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAABAAAAFAAAB34AAAQ2AAAAAgAAABUAAAd9AAAENQAAAAAAAAAAB4AAAAACAAAA
    FQAAB30AAAQ1
  tabs:
  - history:
    - active: true
      last_visited: '2025-04-25T19:43:32'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: User Input - Bash Scripting Tutorial
      url: https://ryanstutorials.net/bash-scripting-tutorial/bash-input.php
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-25T19:43:34'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'mikavilpas/yazi.nvim: A Neovim Plugin for the yazi terminal file manager'
      url: https://github.com/mikavilpas/yazi.nvim
      zoom: 1.0
  - active: true
    history:
    - active: true
      last_visited: '2025-04-25T19:43:34'
      pinned: false
      scroll-pos:
        x: 0
        y: 840
      title: yazi.nvim/documentation/plugin-management.md at main · mikavilpas/yazi.nvim
      url: https://github.com/mikavilpas/yazi.nvim/blob/main/documentation/plugin-management.md
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-25T19:43:33'
      pinned: false
      scroll-pos:
        x: 0
        y: 3000
      title: Configuration | Starship
      url: https://starship.rs/config/
      zoom: 1.0
