windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAABAAAAFAAAB34AAAQ2AAAAAwAAABYAAAd8AAAENAAAAAAAAAAAB4AAAAADAAAA
    FgAAB3wAAAQ0
  tabs:
  - history:
    - active: true
      last_visited: '2025-04-07T15:04:06'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'kassio/neoterm: Wrapper of some vim/neovim''s :terminal functions.'
      url: https://github.com/kassio/neoterm
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-07T15:04:06'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: neoterm/doc/neoterm.txt at master · kassio/neoterm
      url: https://github.com/kassio/neoterm/blob/master/doc/neoterm.txt
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-07T15:04:06'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'tmux-plugins/tmux-cpu: Plug and play cpu percentage and icon indicator
        for Tmux.'
      url: https://github.com/tmux-plugins/tmux-cpu
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-07T15:04:05'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Tmux Cheat Sheet & Quick Reference | Session, window, pane and more
      url: https://tmuxcheatsheet.com/
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-07T15:04:05'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: sys — System-specific parameters and functions — Python 3.13.2 documentation
      url: https://docs.python.org/3/library/sys.html
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-07T15:04:06'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: python linux os module - Google Search
      url: https://www.google.com/search?q=python%20linux%20os%20module
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-04-07T15:04:06'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: getting temps from lm senosr for conky - Google Search
      url: https://www.google.com/search?q=getting+temps+from+lm+senosr+for+conky&sca_esv=4f7b8728d565568a&sxsrf=AHTn8zqN6XaScgSunFZsJzsZBt5cR8xQWw%3A1744051162937&ei=2hv0Z-rxOLubptQP9suckQQ&ved=0ahUKEwjqxqXwyMaMAxW7jYkEHfYlJ0IQ4dUDCBI&uact=5&oq=getting+temps+from+lm+senosr+for+conky&gs_lp=Egxnd3Mtd2l6LXNlcnAiJmdldHRpbmcgdGVtcHMgZnJvbSBsbSBzZW5vc3IgZm9yIGNvbmt5MgUQABjvBTIIEAAYgAQYogQyCBAAGIAEGKIEMgUQABjvBTIIEAAYogQYiQVIvxVQsBJYsBJwAXgBkAEAmAGhAaABoQGqAQMwLjG4AQPIAQD4AQGYAgKgAqcBwgIKEAAYsAMY1gQYR5gDAOIDBRIBMSBAiAYBkAYIkgcDMS4xoAfGBLIHAzAuMbgHowE&sclient=gws-wiz-serp
      zoom: 1.0
  - active: true
    history:
    - active: true
      last_visited: '2025-04-07T15:04:07'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: get correct font names arch - Google Search
      url: https://www.google.com/search?q=get%20correct%20font%20names%20%20arch
      zoom: 1.0
