windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAAAAAAEgAABj8AAAODAAAAAgAAABQAAAY9AAADgQAAAAAAAAAABkAAAAACAAAA
    FAAABj0AAAOB
  tabs:
  - history:
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 11562
      title: Why you should be using fzf, the command line fuzzy finder
      url: https://www.freecodecamp.org/news/fzf-a-command-line-fuzzy-finder-missing-demo-a7de312403ff/
      zoom: 1.0
  - active: true
    history:
    - pinned: false
      title: Alexey Samoshkin - YouTube
      url: https://www.youtube.com/channel/UCfju8u-YOpNMO4CbyzIsc9Q
    - pinned: false
      title: Alexey Samoshkin - YouTube
      url: https://www.youtube.com/channel/UCfju8u-YOpNMO4CbyzIsc9Q/about
    - pinned: false
      title: Alexey Samoshkin - YouTube
      url: https://www.youtube.com/channel/UCfju8u-YOpNMO4CbyzIsc9Q/about
    - pinned: false
      title: Alexey Samoshkin - YouTube
      url: https://www.youtube.com/channel/UCfju8u-YOpNMO4CbyzIsc9Q/about
    - pinned: false
      title: Alexey Samoshkin - YouTube
      url: https://www.youtube.com/channel/UCfju8u-YOpNMO4CbyzIsc9Q/videos
    - pinned: false
      title: Alexey Samoshkin - YouTube
      url: https://www.youtube.com/channel/UCfju8u-YOpNMO4CbyzIsc9Q/videos
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Vim universe. fzf - command line fuzzy finder - YouTube
      url: https://www.youtube.com/watch?v=qgG5Jhi_Els
      zoom: 1.0
    - pinned: false
      title: speedtest cli github at DuckDuckGo
      url: https://duckduckgo.com/?q=speedtest+cli+github&ia=web
    - original-url: https://duckduckgo.com/?q=speedtest+cli+github&ia=web
      pinned: false
      title: 'GitHub - sivel/speedtest-cli: Command line interface for testing internet
        bandwidth using speedtest.net'
      url: https://github.com/sivel/speedtest-cli
  - history:
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'GitHub - junegunn/fzf: A command-line fuzzy finder'
      url: https://github.com/junegunn/fzf#git-ls-tree-for-fast-traversal
      zoom: 1.0
  - history:
    - pinned: false
      title: Examples · junegunn/fzf Wiki · GitHub
      url: https://github.com/junegunn/fzf/wiki/examples#cd
    - pinned: false
      title: enable preview window in fzf only in file find mode at DuckDuckGo
      url: https://duckduckgo.com/?q=enable+preview+window+in+fzf+only+in+file+find+mode&ia=software
    - pinned: false
      title: enable preview window in fzf at DuckDuckGo
      url: https://duckduckgo.com/?q=enable+preview+window+in+fzf&ia=software
    - active: true
      original-url: https://duckduckgo.com/?q=enable+preview+window+in+fzf&ia=software
      pinned: false
      scroll-pos:
        x: 0
        y: 430
      title: Key bindings for git with fzf
      url: https://junegunn.kr/2016/07/fzf-git/
      zoom: 1.0
  - history:
    - pinned: false
      title: Key bindings for git with fzf (https://junegunn.kr/2016/07/fzf-git/)
        · GitHub
      url: https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 400
      title: Key bindings for git with fzf (https://junegunn.kr/2016/07/fzf-git/)
        · GitHub
      url: https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236#file-key-binding-zsh
      zoom: 1.0
    - original-url: https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236/raw/be535c93284afde06342526de9476eb15071e78a/key-binding.zsh
      pinned: false
      title: https://gist.githubusercontent.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236/raw/be535c93284afde06342526de9476eb15071e78a/key-binding.zsh
      url: https://gist.githubusercontent.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236/raw/be535c93284afde06342526de9476eb15071e78a/key-binding.zsh
  - history:
    - pinned: false
      title: Examples · junegunn/fzf Wiki · GitHub
      url: https://github.com/junegunn/fzf/wiki/examples#cd
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 2960
      title: 'GitHub - junegunn/fzf: A command-line fuzzy finder'
      url: https://github.com/junegunn/fzf
      zoom: 1.0
  - history:
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 12872
      title: 'GitHub - junegunn/fzf: A command-line fuzzy finder'
      url: https://github.com/junegunn/fzf#options
      zoom: 1.0
  - history:
    - pinned: false
      title: 'GitHub - junegunn/fzf: A command-line fuzzy finder'
      url: https://github.com/junegunn/fzf#examples
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 3560
      title: Examples · junegunn/fzf Wiki · GitHub
      url: https://github.com/junegunn/fzf/wiki/examples
      zoom: 1.0
  - history:
    - pinned: false
      title: Home · junegunn/fzf Wiki · GitHub
      url: https://github.com/junegunn/fzf/wiki
    - pinned: false
      title: fasd zsh at DuckDuckGo
      url: https://duckduckgo.com/?q=fasd+zsh&ia=software
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 3317
      title: 'GitHub - clvv/fasd: Command-line productivity booster, offers quick
        access to files and directories, inspired by autojump, z and v.'
      url: https://github.com/clvv/fasd
      zoom: 1.0
