#!/bin/bash - 
#===============================================================================
#
#          FILE: dmenu_man.sh
# 
#         USAGE: ./dmenu_man.sh 
# 
#   DESCRIPTION: 
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Adam Ortell (), arortell@gmail.com
#  ORGANIZATION: 
#       CREATED: 12/03/2017 09:04:18 AM
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

page=$(apropos . \
       | cut -d' ' -f1 \
       | sort -d \
       | uniq \
       | dmenu -l 20 -p 'Man Page' \
       | cut -d':' -f3-)
#terminology --name=_scratch --title=_scratch -e man "$page"

[[ $page  ]]
apropos . | cut -d' ' -f1 | grep -q "$page"
terminology  -e man "$page"

