#!/bin/bash -
#===============================================================================
#
#          FILE: panel2.sh
#
#         USAGE: ./panel2.sh
#
#   DESCRIPTION: 
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Adam Ortell (), arortell80@gmail.com
#  ORGANIZATION: 
#       CREATED: 10/26/2018 03:36:38 PM
#      REVISION:  ---
#===============================================================================

set -o nounset                                  # Treat unset variables as an error
set -eo pipefail                                # exit if ANY command fails,errors from pipe

progname="$(basename "$0")"                     # name of script

[[ $0 == /* ]] && script="$0" || script="${PWD}/${0#./}"
panelfolder=${script%/*}
trap 'herbstclient emit_hook quit_panel' TERM
herbstclient pad 0 24
herbstclient emit_hook quit_panel

dzen2 -p -h 1 -w 166 -x 0 -y 23 -bg '#afdf87' &
pids+=($!)

"$panelfolder/tray.sh" &
pids+=($!)

"$panelfolder/tags.sh" &
pids+=($!)

conky -c "$panelfolder/conkyrc" &
pids+=($!)

herbstclient --wait '^(quit_panel|reload).*'
kill -TERM "${pids[@]}" >/dev/null 2>&1
exit 0
