# Base path for local files to be synced
local_base_path: /path/to/your/local/base/directory

# If this file is updated then on the next sync run a resync is done. This file applies global to all sync jobs. This is because rclone requires a resync after any filter change.
exclusion_rules_file: /path/to/your/filter.txt

# Redirect rclone log output
redirect_rclone_log_output: true

# CPU usage limit as a percentage
max_cpu_usage_percent: 100

# Run missed jobs
run_missed_jobs: true

# Run initial sync on startup
run_initial_sync_on_startup: true

# Define the paths to be synchronized
sync_jobs:
  example_job:
    local: example_folder
    rclone_remote: your_remote
    remote: path/on/remote/storage
    schedule: "*/30 * * * *" # Every 30 minutes
    dry_run: false
    rclone_options:
      log_level: Notice
  example_job_2:
    local: another_folder
    rclone_remote: second_remote
    remote: another/path/on/remote
    schedule: "0 */2 * * *" # Every 2 hours
    dry_run: false
    rclone_options: # Overriding the default options
      log_level: Notice

# Rclone options
rclone_options:
  recover: null
  resilient: null
  max_delete: 5
  log_level: INFO
  max_lock: 15m
  retries: 3
  low_level_retries: 10
  compare: "size,modtime,checksum"
  create_empty_src_dirs: null
  check_access: null
  exclude:
    - "*.tmp"
    - "*.log"
    - "._*"
    - ".DS_Store"
    - ".Spotlight-V100/**"
    - ".Trashes/**"
    - ".fseventsd/**"
    - ".AppleDouble/**"
    - ".VolumeIcon.icns"

# Bisync-specific options
bisync_options:
  conflict_resolve: newer
  conflict_loser: num
  conflict_suffix: rc-conflict
  track_renames: null
  # Add any additional bisync-specific options here
  # custom_bisync_option: value

# Resync-specific options
resync_options:
  error_on_no_transfer: null
  # Add any additional resync-specific options here
  # custom_resync_option: value